# Github Action - Dev branch
name: Workflow - Dev Branch

# Conditions for running the workflow.
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  bunch_of_echo_statements:
    runs-on: self-hosted

    steps:
      - name: Print 'Hello World'
        run: echo "Hello World!!!"

      - name: Print additional statements
        run: |
          echo "This is an extra echo statement!"
          echo "Self-hosted runner werkt correct."

  download_repository:
    runs-on: self-hosted

    steps:
      - name: Retreive the repository
        uses: actions/checkout@v4
