name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - dev     # Runs validation only
      - main    # Runs full deployment
      - destroy # Runs Terraform destroy
  workflow_dispatch:  # Allows manual execution

jobs:
  debug-info:
    name: "Debug GitHub Actions Environment"
    runs-on: ubuntu-latest

    steps:
      - name: Print GitHub Environment Variables
        run: |
          echo "GitHub ref: $GITHUB_REF"
          echo "GitHub event name: $GITHUB_EVENT_NAME"
          echo "GitHub ref name: ${GITHUB_REF#refs/heads/}"
          echo "GitHub repository: $GITHUB_REPOSITORY"

  terraform-validate:
    name: "Terraform Validate (Dev & Main)"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'  # FIXED

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configur

