name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - dev     # Runs validation only
      - main    # Runs full deployment
      - destroy # Runs Terraform destroy
  workflow_dispatch:  # Allows manual execution

jobs:
  debug-info:
    name: "Debug GitHub Actions Environment"
    runs-on: ubuntu-latest

    steps:
      - name: Print GitHub Environment Variables
        run: |
          echo "GitHub ref: $GITHUB_REF"
          echo "GitHub event name: $GITHUB_EVENT_NAME"
          echo "GitHub ref name: ${GITHUB_REF#refs/heads/}"
          echo "GitHub repository: $GITHUB_REPOSITORY"

  terraform-validate:
    name: "Terraform Validate (Dev)"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.event_name == 'workflow_dispatch'  # Ensures only dev or manual runs

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Configuration
        run: terraform validate

  terraform-deploy:
    name: "Terraform Deploy (Main)"
    runs-on: ubuntu-latest
    needs: [debug-info, terraform-validate]  # Ensures debug runs first
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

  terraform-destroy:
    name: "Terraform Destroy (Destroy Branch)"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/destroy' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Initialize Terraform
        run: terraform init

      - name: Destroy Terraform Infrastructure
        run: terraform destroy -auto-approve

